#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# GpuViewR — master install (v0.5+)
#
# One-liner:
#   curl -fsSL https://raw.githubusercontent.com/Erreur32/GpuViewR/main/install.sh | bash
#
# What it does:
#   1. Detects the local GPU vendor (nvidia-smi, then rocm-smi).
#   2. Downloads docker-compose.yaml from the repo into ~/gpuviewr/.
#   3. Generates ~/gpuviewr/.env with random JWT_SECRET + bootstrap
#      token + LAN IP + COMPOSE_PROFILES=<vendor>.
#   4. Runs `docker compose up -d` and prints the URL.
#
# Idempotent: re-running on an existing install keeps the .env intact
# and only pulls the latest compose + restarts.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors (disable in non-TTY) ────────────────────────────────────────────────
if [ -t 1 ]; then
  R="\033[0m"; B="\033[1m"; G="\033[32m"; Y="\033[33m"; C="\033[36m"; RED="\033[31m"
else
  R=""; B=""; G=""; Y=""; C=""; RED=""
fi

# Install dir resolution, in priority order:
#   1. GPUVIEWR_INSTALL_DIR env  → explicit override, always wins.
#   2. $PWD if it looks intentional → user has cd'd into a dir they
#      chose (mkdir /home/docker/gpuviewr && cd into it, etc.). We
#      respect it. The "looks intentional" filter excludes places that
#      are usually the SSH landing point or session scratch, not where
#      you'd want a service install:
#          /  $HOME  /root  /tmp
#   3. $HOME/gpuviewr → legacy default for the lazy curl|bash case.
if [ -n "${GPUVIEWR_INSTALL_DIR:-}" ]; then
  INSTALL_DIR="$GPUVIEWR_INSTALL_DIR"
  INSTALL_REASON="from \$GPUVIEWR_INSTALL_DIR"
elif [ "$PWD" = "/" ] || [ "$PWD" = "$HOME" ] || [ "$PWD" = "/tmp" ] || [ "$PWD" = "/root" ]; then
  INSTALL_DIR="$HOME/gpuviewr"
  INSTALL_REASON="default — \$PWD '$PWD' is a session landing dir; cd into a target dir or set GPUVIEWR_INSTALL_DIR=… to override"
else
  INSTALL_DIR="$PWD"
  INSTALL_REASON="from current \$PWD"
fi
BRANCH="${GPUVIEWR_BRANCH:-main}"
RAW_URL="https://raw.githubusercontent.com/Erreur32/GpuViewR/${BRANCH}"

echo ""
echo -e "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${R}"
echo -e "${C}${B}  GpuViewR — master install${R}"
echo -e "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${R}"
echo ""
echo -e "  ${C}Install directory:${R} ${B}${INSTALL_DIR}${R}  ${Y}(${INSTALL_REASON})${R}"
echo ""

# ── Preflight ────────────────────────────────────────────────────────────────
need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo -e "${RED}Error:${R} required command '$1' not found in PATH."
    exit 1
  }
}
need curl
need docker
docker compose version >/dev/null 2>&1 || {
  echo -e "${RED}Error:${R} 'docker compose' v2 plugin is required (older 'docker-compose' v1 not supported)."
  exit 1
}

# ── Vendor detection ─────────────────────────────────────────────────────────
VENDOR=""
if command -v nvidia-smi >/dev/null 2>&1; then
  VENDOR="nvidia"
  echo -e "  ${G}✓${R} Detected NVIDIA GPU (nvidia-smi present)"
elif command -v rocm-smi >/dev/null 2>&1 || [ -x /opt/rocm/bin/rocm-smi ]; then
  VENDOR="amd"
  echo -e "  ${G}✓${R} Detected AMD GPU (rocm-smi present)"
else
  echo -e "  ${Y}○${R} No nvidia-smi or rocm-smi found on this host."
  echo -e "  ${Y}○${R} Installing in aggregator-only mode (hub-only, no local GPU)."
  echo -e "  ${Y}○${R} Remote agents can still enroll via the UI to feed this hub."
fi

# ── Working dir ──────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
echo -e "  ${G}✓${R} Install dir: ${C}${INSTALL_DIR}${R}"

# ── .env (generated BEFORE docker-compose.yaml so any subsequent
# `docker compose` invocation finds JWT_SECRET / LOCAL_AGENT_BOOTSTRAP
# already set — kills the WARN[0000] noise on re-installs over a
# running stack) ─────────────────────────────────────────────────────
if [ ! -f .env ]; then
  HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
  HUB_HOSTNAME="$(hostname)"
  TZ="$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo 'Europe/Paris')"
  JWT_SECRET_VAL="$(openssl rand -base64 32)"
  LOCAL_AGENT_BOOTSTRAP_VAL="$(openssl rand -base64 32)"

  cat > .env <<EOF
# GpuViewR master configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Secret used to sign JWTs. Rotate via \`docker compose down && openssl rand -base64 32 > .env-new\`.
JWT_SECRET=${JWT_SECRET_VAL}

# Shared-secret consumed by the local sidecar agent for bootstrap auth.
# Leave empty (or remove the line) to disable the sidecar entirely
# and run the hub as a pure aggregator for remote agents.
LOCAL_AGENT_BOOTSTRAP=${LOCAL_AGENT_BOOTSTRAP_VAL}

# Public IP printed in the boot banner. Auto-detected; override for VPN / multi-NIC hosts.
HOST_IP=${HOST_IP}

# Real hostname recovered inside the container. Override if /etc/hostname returns something weird.
HUB_HOSTNAME=${HUB_HOSTNAME}

# Host port mapped to the container's 3015. Change if 7510 conflicts.
DASHBOARD_PORT=7510

# Container timezone (for log timestamps).
TZ=${TZ}

# How long historical metrics live in SQLite.
RETENTION_DAYS=7

# Vendor profile picked by install.sh. Switch by editing this line and
# re-running 'docker compose up -d'. Empty = aggregator-only (no
# sidecar agent for the local host).
COMPOSE_PROFILES=${VENDOR}

# AMD-only — override if 'getent group video render' on this host
# shows different numeric GIDs (ROCm installs sometimes shift render
# to 992).
# VIDEO_GID=44
# RENDER_GID=109
EOF
  chmod 600 .env
  echo -e "  ${G}✓${R} Generated ${C}.env${R} (mode 600). COMPOSE_PROFILES=${C}${VENDOR:-empty}${R}"
else
  # Preserve user customisations. Auto-fix COMPOSE_PROFILES if the
  # detected vendor changed (e.g. user swapped the GPU), and back-fill
  # any required secret that's missing because the .env predates the
  # variable's introduction (e.g. LOCAL_AGENT_BOOTSTRAP arrived in
  # v0.5.0 — older .env files don't have it and the sidecar crash-loops
  # with "Missing required env var: AGENT_TOKEN" on upgrade).
  echo -e "  ${Y}○${R} ${C}.env${R} already exists — preserving secrets + customisations."

  # Back-fill missing required secrets. Existing values are never
  # touched; only absent lines are appended.
  if ! grep -q "^JWT_SECRET=" .env 2>/dev/null; then
    {
      echo ""
      echo "# Back-filled by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — missing from older .env."
      echo "JWT_SECRET=$(openssl rand -base64 32)"
    } >> .env
    echo -e "  ${G}✓${R} Back-filled missing ${C}JWT_SECRET${R}."
  fi
  if ! grep -q "^LOCAL_AGENT_BOOTSTRAP=" .env 2>/dev/null; then
    {
      echo ""
      echo "# Back-filled by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — missing from older .env."
      echo "LOCAL_AGENT_BOOTSTRAP=$(openssl rand -base64 32)"
    } >> .env
    echo -e "  ${G}✓${R} Back-filled missing ${C}LOCAL_AGENT_BOOTSTRAP${R} (sidecar agent token)."
  fi

  if [ -n "$VENDOR" ] && ! grep -q "^COMPOSE_PROFILES=${VENDOR}\$" .env 2>/dev/null; then
    if grep -q "^COMPOSE_PROFILES=" .env 2>/dev/null; then
      # Replace existing line (cross-platform: write to tmp + mv)
      sed -i.bak "s|^COMPOSE_PROFILES=.*|COMPOSE_PROFILES=${VENDOR}|" .env && rm -f .env.bak
      echo -e "  ${G}✓${R} Auto-updated COMPOSE_PROFILES to ${C}${VENDOR}${R} (detected vendor changed)."
    else
      echo "COMPOSE_PROFILES=${VENDOR}" >> .env
      echo -e "  ${G}✓${R} Appended COMPOSE_PROFILES=${C}${VENDOR}${R} to .env."
    fi
  fi
fi

# Export the env vars from .env into THIS shell so any docker compose
# invocation below has them — even before compose itself loads .env.
# This is the line that finally kills the "JWT_SECRET variable not set"
# WARN on re-installs.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# ── Pull docker-compose.yaml ────────────────────────────────────────
# Behaviour matrix:
#   - No existing file       → fetch silently.
#   - Existing file == remote → "already up to date", no prompt.
#   - Existing file ≠ remote  → show diff (first 40 lines), prompt
#                                Y/n before overwriting, back up the
#                                old file. If no TTY is reachable
#                                (CI, true `curl | bash` without
#                                /dev/tty) we keep the existing file
#                                and print the URL so the operator
#                                can merge manually. Reason: users
#                                regularly customise the compose
#                                (env additions, port remaps, extra
#                                volumes). Silent overwrite — what
#                                this script did pre-v0.7.4 — wiped
#                                those edits on every re-run.
COMPOSE_URL="${RAW_URL}/docker-compose.yaml"
prompt_yn() {
  local msg="$1"
  local yn=""
  if [ -e /dev/tty ]; then
    read -r -p "$msg [y/N] " yn </dev/tty
  fi
  case "$yn" in
    [yY]*) return 0 ;;
    *)     return 1 ;;
  esac
}

if [ -f docker-compose.yaml ]; then
  TMP_COMPOSE=$(mktemp)
  if ! curl -fsSL -o "$TMP_COMPOSE" "$COMPOSE_URL"; then
    rm -f "$TMP_COMPOSE"
    echo -e "  ${Y}!${R} Failed to fetch the latest docker-compose.yaml from $COMPOSE_URL — keeping existing file."
  elif cmp -s docker-compose.yaml "$TMP_COMPOSE"; then
    echo -e "  ${G}✓${R} docker-compose.yaml already up to date"
    rm -f "$TMP_COMPOSE"
  else
    echo -e "  ${Y}!${R} Existing docker-compose.yaml differs from branch ${C}${BRANCH}${R}. Diff (first 40 lines):"
    echo -e "${Y}---${R}"
    diff -u docker-compose.yaml "$TMP_COMPOSE" | head -40 || true
    echo -e "${Y}---${R}"
    if prompt_yn "Overwrite docker-compose.yaml with the version from main? Your file will be backed up first."; then
      BACKUP="docker-compose.yaml.bak.$(date +%Y%m%d-%H%M%S)"
      cp docker-compose.yaml "$BACKUP"
      mv "$TMP_COMPOSE" docker-compose.yaml
      echo -e "  ${G}→${R} docker-compose.yaml updated. Old version saved as ${C}${BACKUP}${R}"
    else
      rm -f "$TMP_COMPOSE"
      echo -e "  ${B}→${R} Keeping your existing docker-compose.yaml."
      echo -e "    If you want to merge upstream changes manually later, fetch ${C}${COMPOSE_URL}${R}"
      echo -e "    and diff against your file."
    fi
  fi
else
  echo -e "  ${B}→${R} Fetching docker-compose.yaml from branch ${C}${BRANCH}${R}..."
  curl -fsSL -o docker-compose.yaml "$COMPOSE_URL"
fi

# ── Detect existing stack & warn before destructive recreate ─────────────────
# We're about to run `docker compose up -d --force-recreate
# --remove-orphans`, which stops, removes, and replaces every
# container in the compose project. That's a ~5-10 s downtime on
# the dashboard plus a brief sample gap on every connected agent.
# For a fresh install (no existing containers) there's nothing to
# warn about — just proceed. For an upgrade, list what's going to
# be replaced/removed and prompt.
EXISTING=$(docker compose ps --all -q 2>/dev/null || true)
if [ -n "$EXISTING" ]; then
  NCONT=$(echo "$EXISTING" | wc -l | tr -d ' ')
  echo ""
  echo -e "  ${Y}!${R} Existing GpuViewR stack detected — ${B}${NCONT}${R} container(s) in this project:"
  docker compose ps --format 'table {{.Service}}\t{{.Name}}\t{{.Status}}' 2>/dev/null | sed 's/^/      /' || true
  echo ""
  echo -e "    The next step recreates these with ${C}--force-recreate --remove-orphans${R}:"
  echo -e "      • brief downtime (~5-10 s) on the dashboard"
  echo -e "      • any orphan container (e.g. pre-v0.7.3 ${C}gpuviewr-agent-local${R}) will be removed"
  echo -e "      • your data volume (${C}./data${R}) is preserved"
  if ! prompt_yn "Proceed with pull + force-recreate?"; then
    echo -e "  ${B}→${R} Aborted by user. To finish manually when ready:"
    echo -e "    ${C}cd ${INSTALL_DIR} && docker compose pull && docker compose up -d --force-recreate --remove-orphans${R}"
    exit 0
  fi
fi

# ── Up ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${B}→${R} Pulling images..."
# Native compose progress — the user sees image layers downloading
# in real time. The WARN env-var noise that used to leak here is
# killed by the .env-before-curl + export step earlier in this script.
docker compose pull || true

echo -e "  ${B}→${R} Starting stack..."
# --force-recreate so reruns pick up compose-level changes (volume
# adds, env additions, container_name changes — the last one bit us
# on v0.7.3 when the sidecar was renamed gpuviewr-agent-local →
# gpuviewr-hub-agent and rerunning the installer without
# --force-recreate left the old container orphaned).
# --remove-orphans cleans up renamed-out containers cleanly.
docker compose up -d --force-recreate --remove-orphans

# ── Final hint ───────────────────────────────────────────────────────────────
IP="$(grep '^HOST_IP=' .env | cut -d= -f2-)"
[ -z "$IP" ] && IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
PORT="$(grep '^DASHBOARD_PORT=' .env | cut -d= -f2- || echo 7510)"
echo ""
echo -e "${G}${B}Done.${R}"
echo -e "  ${B}Hub:${R}    ${C}http://${IP}:${PORT}${R}"
echo -e "  ${B}First user becomes admin.${R}"
[ -n "$VENDOR" ] && echo -e "  ${B}Sidecar:${R} ${C}${VENDOR}${R} agent connected automatically via bootstrap token."
echo ""
echo -e "  Logs:    ${C}cd ${INSTALL_DIR} && docker compose logs -f${R}"
echo -e "  Update:  ${C}cd ${INSTALL_DIR} && docker compose pull && docker compose up -d${R}"
echo -e "  Stop:    ${C}cd ${INSTALL_DIR} && docker compose down${R}"
echo ""
