#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# GpuViewR — master install (v0.5+)
#
# One-liner:
#   curl -fsSL https://raw.githubusercontent.com/Erreur32/GpuViewR/main/install.sh | bash
#
# What it does:
#   1. Detects the local GPU vendor (nvidia-smi, then rocm-smi).
#   2. Downloads docker-compose.yaml from the repo into ~/gpuviewr/.
#   3. Generates ~/gpuviewr/.env with random JWT_SECRET + bootstrap
#      token + LAN IP + COMPOSE_PROFILES=<vendor>.
#   4. Runs `docker compose up -d` and prints the URL.
#
# Idempotent: re-running on an existing install keeps the .env intact
# and only pulls the latest compose + restarts.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors (disable in non-TTY) ────────────────────────────────────────────────
if [ -t 1 ]; then
  R="\033[0m"; B="\033[1m"; G="\033[32m"; Y="\033[33m"; C="\033[36m"; RED="\033[31m"
else
  R=""; B=""; G=""; Y=""; C=""; RED=""
fi

# Install dir resolution, in priority order:
#   1. GPUVIEWR_INSTALL_DIR env  → explicit override, always wins.
#   2. $PWD if it looks intentional → user has cd'd into a dir they
#      chose (mkdir /home/docker/gpuviewr && cd into it, etc.). We
#      respect it. The "looks intentional" filter excludes places that
#      are usually the SSH landing point or session scratch, not where
#      you'd want a service install:
#          /  $HOME  /root  /tmp
#   3. $HOME/gpuviewr → legacy default for the lazy curl|bash case.
if [ -n "${GPUVIEWR_INSTALL_DIR:-}" ]; then
  INSTALL_DIR="$GPUVIEWR_INSTALL_DIR"
elif [ "$PWD" = "/" ] || [ "$PWD" = "$HOME" ] || [ "$PWD" = "/tmp" ] || [ "$PWD" = "/root" ]; then
  INSTALL_DIR="$HOME/gpuviewr"
else
  INSTALL_DIR="$PWD"
fi
BRANCH="${GPUVIEWR_BRANCH:-main}"
RAW_URL="https://raw.githubusercontent.com/Erreur32/GpuViewR/${BRANCH}"

echo ""
echo -e "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${R}"
echo -e "${C}${B}  GpuViewR — master install${R}"
echo -e "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${R}"
echo ""

# ── Preflight ────────────────────────────────────────────────────────────────
need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo -e "${RED}Error:${R} required command '$1' not found in PATH."
    exit 1
  }
}
need curl
need docker
docker compose version >/dev/null 2>&1 || {
  echo -e "${RED}Error:${R} 'docker compose' v2 plugin is required (older 'docker-compose' v1 not supported)."
  exit 1
}

# ── Vendor detection ─────────────────────────────────────────────────────────
VENDOR=""
if command -v nvidia-smi >/dev/null 2>&1; then
  VENDOR="nvidia"
  echo -e "  ${G}✓${R} Detected NVIDIA GPU (nvidia-smi present)"
elif command -v rocm-smi >/dev/null 2>&1 || [ -x /opt/rocm/bin/rocm-smi ]; then
  VENDOR="amd"
  echo -e "  ${G}✓${R} Detected AMD GPU (rocm-smi present)"
else
  echo -e "  ${Y}○${R} No nvidia-smi or rocm-smi found on this host."
  echo -e "  ${Y}○${R} Installing in aggregator-only mode (hub-only, no local GPU)."
  echo -e "  ${Y}○${R} Remote agents can still enroll via the UI to feed this hub."
fi

# ── Working dir ──────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
echo -e "  ${G}✓${R} Install dir: ${C}${INSTALL_DIR}${R}"

# ── .env (generated BEFORE docker-compose.yaml so any subsequent
# `docker compose` invocation finds JWT_SECRET / LOCAL_AGENT_BOOTSTRAP
# already set — kills the WARN[0000] noise on re-installs over a
# running stack) ─────────────────────────────────────────────────────
if [ ! -f .env ]; then
  HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
  HUB_HOSTNAME="$(hostname)"
  TZ="$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo 'Europe/Paris')"
  JWT_SECRET_VAL="$(openssl rand -base64 32)"
  LOCAL_AGENT_BOOTSTRAP_VAL="$(openssl rand -base64 32)"

  cat > .env <<EOF
# GpuViewR master configuration — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Secret used to sign JWTs. Rotate via \`docker compose down && openssl rand -base64 32 > .env-new\`.
JWT_SECRET=${JWT_SECRET_VAL}

# Shared-secret consumed by the local sidecar agent for bootstrap auth.
# Leave empty (or remove the line) to disable the sidecar entirely
# and run the hub as a pure aggregator for remote agents.
LOCAL_AGENT_BOOTSTRAP=${LOCAL_AGENT_BOOTSTRAP_VAL}

# Public IP printed in the boot banner. Auto-detected; override for VPN / multi-NIC hosts.
HOST_IP=${HOST_IP}

# Real hostname recovered inside the container. Override if /etc/hostname returns something weird.
HUB_HOSTNAME=${HUB_HOSTNAME}

# Host port mapped to the container's 3015. Change if 7510 conflicts.
DASHBOARD_PORT=7510

# Container timezone (for log timestamps).
TZ=${TZ}

# How long historical metrics live in SQLite.
RETENTION_DAYS=7

# Vendor profile picked by install.sh. Switch by editing this line and
# re-running 'docker compose up -d'. Empty = aggregator-only (no
# sidecar agent for the local host).
COMPOSE_PROFILES=${VENDOR}

# AMD-only — override if 'getent group video render' on this host
# shows different numeric GIDs (ROCm installs sometimes shift render
# to 992).
# VIDEO_GID=44
# RENDER_GID=109
EOF
  chmod 600 .env
  echo -e "  ${G}✓${R} Generated ${C}.env${R} (mode 600). COMPOSE_PROFILES=${C}${VENDOR:-empty}${R}"
else
  # Preserve user customisations. Auto-fix COMPOSE_PROFILES if the
  # detected vendor changed (e.g. user swapped the GPU) — that one
  # line is install.sh's responsibility, all the other secrets +
  # tunables in .env stay untouched.
  echo -e "  ${Y}○${R} ${C}.env${R} already exists — preserving secrets + customisations."
  if [ -n "$VENDOR" ] && ! grep -q "^COMPOSE_PROFILES=${VENDOR}\$" .env 2>/dev/null; then
    if grep -q "^COMPOSE_PROFILES=" .env 2>/dev/null; then
      # Replace existing line (cross-platform: write to tmp + mv)
      sed -i.bak "s|^COMPOSE_PROFILES=.*|COMPOSE_PROFILES=${VENDOR}|" .env && rm -f .env.bak
      echo -e "  ${G}✓${R} Auto-updated COMPOSE_PROFILES to ${C}${VENDOR}${R} (detected vendor changed)."
    else
      echo "COMPOSE_PROFILES=${VENDOR}" >> .env
      echo -e "  ${G}✓${R} Appended COMPOSE_PROFILES=${C}${VENDOR}${R} to .env."
    fi
  fi
fi

# Export the env vars from .env into THIS shell so any docker compose
# invocation below has them — even before compose itself loads .env.
# This is the line that finally kills the "JWT_SECRET variable not set"
# WARN on re-installs.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

# ── Pull docker-compose.yaml ────────────────────────────────────────
echo -e "  ${B}→${R} Pulling docker-compose.yaml from branch ${C}${BRANCH}${R}..."
curl -fsSL -o docker-compose.yaml "${RAW_URL}/docker-compose.yaml"

# ── Up ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${B}→${R} Pulling images..."
# Native compose progress — the user sees image layers downloading
# in real time. The WARN env-var noise that used to leak here is
# killed by the .env-before-curl + export step earlier in this script.
docker compose pull || true

echo -e "  ${B}→${R} Starting stack..."
docker compose up -d

# ── Final hint ───────────────────────────────────────────────────────────────
IP="$(grep '^HOST_IP=' .env | cut -d= -f2-)"
[ -z "$IP" ] && IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
PORT="$(grep '^DASHBOARD_PORT=' .env | cut -d= -f2- || echo 7510)"
echo ""
echo -e "${G}${B}Done.${R}"
echo -e "  ${B}Hub:${R}    ${C}http://${IP}:${PORT}${R}"
echo -e "  ${B}First user becomes admin.${R}"
[ -n "$VENDOR" ] && echo -e "  ${B}Sidecar:${R} ${C}${VENDOR}${R} agent connected automatically via bootstrap token."
echo ""
echo -e "  Logs:    ${C}cd ${INSTALL_DIR} && docker compose logs -f${R}"
echo -e "  Update:  ${C}cd ${INSTALL_DIR} && docker compose pull && docker compose up -d${R}"
echo -e "  Stop:    ${C}cd ${INSTALL_DIR} && docker compose down${R}"
echo ""
