sonar.projectKey=Erreur32_GpuViewR2
sonar.organization=erreur32

sonar.projectName=GpuViewR
sonar.projectVersion=0.1.35

# Sources
sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*,**/coverage/**

# Exclude all sources from coverage (no test suite yet)
sonar.coverage.exclusions=**/*

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
