import 'dotenv/config';

export const config = {
  port: Number.parseInt(process.env.PORT || '3015', 10),
  jwtSecret: process.env.JWT_SECRET || '',
  publicUrl: process.env.PUBLIC_URL || '',
  tz: process.env.TZ || 'UTC',
  gpuTickMs: Number.parseInt(process.env.GPU_TICK_MS || '1000', 10),
  // 'auto' probes nvidia-smi then rocm-smi at boot. Explicit 'nvidia'
  // or 'amd' forces the corresponding collector even if both binaries
  // happen to be installed. Boot-time selection lives in
  // server/index.ts (J3 of the AMD master mode plan).
  // Bootstrap secret for the local sidecar agent. When set, an agent
  // presenting this token + host_id=LOCAL_HOST_ID is auto-enrolled
  // (row upserted as kind='agent') without going through the UI
  // enrollment flow. Generated by install.sh; left empty in
  // aggregator-only mode (no local sidecar).
  localAgentBootstrap: process.env.LOCAL_AGENT_BOOTSTRAP || '',
  retentionDays: Number.parseInt(process.env.RETENTION_DAYS || '7', 10),
  dataDir: process.env.DATA_DIR || './data',
  nodeEnv: process.env.NODE_ENV || 'development',
  // Synthetic data for dev hosts without a GPU. Disabled in production
  // unless explicitly forced (FORCE=1) — protects against accidentally
  // serving fake metrics from a real install.
  mockGpu:
    (process.env.MOCK_GPU === '1' || process.env.MOCK_GPU === 'true') &&
    (process.env.NODE_ENV !== 'production' || process.env.MOCK_GPU_FORCE === '1'),
};

if (!config.jwtSecret || config.jwtSecret.length < 16) {
  if (config.nodeEnv === 'production') {
    throw new Error(
      'JWT_SECRET is required in production. Generate one with: openssl rand -base64 32'
    );
  }
  console.warn('[config] JWT_SECRET is missing or too short: using a dev fallback. DO NOT use in production.');
  config.jwtSecret = 'dev-only-insecure-secret-change-me-please-________________';
}

/** Returns PUBLIC_URL if explicitly configured, otherwise an empty string. */
export function getPublicUrl(): string {
  return config.publicUrl || '';
}
